# Generated by Django 4.1.7 on 2023-04-18 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('narx', models.FloatField()),
                ('kelgan_sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Nashryot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('manzil', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sotuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now=True)),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kitob')),
                ('sotuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.sotuvchi')),
            ],
        ),
        migrations.AddField(
            model_name='kitob',
            name='nashryot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.nashryot'),
        ),
    ]
